### ISSUE TITLE
L1 Tests: Some issues noticed during vComponent testing

### ISSUE THREAD

**Issue by sramani-metro** [rdkcentral/rdk-halif-test-hdmi_cec#31]
1. In test_hdmicec_hal_l1_removeLogicalAddress_sinkDevice_negative(), HdmiCecRemoveLogicalAddress() is called thrice in a row. But the result of the second call is expected to be SUCCESS. HdmiCecAddLogicalAddress may have been missed to be called.
2. What is the expected return value of HdmiCecRemoveLogicalAddress() when it is called a second time? Is it HDMI_CEC_IO_ALREADY_REMOVED or HDMI_CEC_IO_NOT_ADDED? There is a couple of places where this is being checked.

**Comment by sramani-metro** [comment]
[hdmicec_testpack_fixes.patch](https://github.com/user-attachments/files/15837224/hdmicec_testpack_fixes.patch)

Adding a patch for the changes

**Comment by srinivasgtl** [comment]
Hi @sramani-metro ,  Thanks for bringing up these issues.

Q1. HdmiCECRemoveLogicalAddress with 0xF as the logical address:  Yes, it's a bit of a grey area in handling this, given that the default logical address assigned is 0xf when we remove any valid logical address. Since the logical address itself is 0xf in this case, it may be quite obvious to decide whether to remove it or not. However, since 0xf is considered the default logical address, I suggest treating this as a failure with the input param. We can discuss this further with the Architects as well.

Q2: HDMI_CEC_IO_ALREADY_REMOVED:  This error code is nowhere used, but still it is part of HDMI_CEC_STATUS.  We can deprecate this error status code as it is no longer required.  

Thanks.

**Comment by akhilbhas** [comment]
hi @sramani-metro , @srinivasgtl ,

test_hdmicec_hal_l1_removeLogicalAddress_sinkDevice_negative() - We have removed the additional call of HdmiCecRemoveLogicalAddress, Added enhanced error code check for HDMI_CEC_IO_NOT_ADDED when logical address remove is called before calling HdmiCecAddLogicalAddress

HDMI_CEC_IO_NOT_ADDED is expected when HdmiCecAddLogicalAddress is not called for the handle before HdmiCecRemoveLogicalAddress , and HDMI_CEC_IO_ALREADY_REMOVED when HdmiCecRemoveLogicalAddress is called a second time or further after calling HdmiCecAddLogicalAddress

Both issues are addressed as part of test update for the latest interface file (https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/issues/36)

PR: https://github.com/rdkcentral/rdk-halif-test-hdmi_cec/pull/38

**Comment by srinivasgtl** [comment]
This issue can be now closed as the changes are now considered on PR #38
